### PR TITLE
Improve reported results

### PR DESCRIPTION
**Pull request by kupietz**

### CODE REVIEW

**Comment by teoric** [comment]
The current change uses the JSON error log as indicator for validity.  Would it make sense to keep boolean state in the error handler, `boolean valid = true`, and set it to `false` on the first exception? (As the handler is instantiated for every validation, there would be no interference.)
Then we could use `keepTrack` as intended for signalling that a JSON log is constructed?

**Comment by teoric** [comment]
Printing the `errorMap` should not be necessary as it is written as JSON and Exceptions are logged, see `addException`.

**Comment by teoric** [comment]
Cherry-picked c99aecd and 5ee878d for now, and implemented validity state

**Comment by kupietz** [comment]
> Cherry-picked [c99aecd](https://github.com/teoric/dtdvalidator/commit/c99aecdb0fee9943bac5561f476362e3f6a266ad) and [5ee878d](https://github.com/teoric/dtdvalidator/commit/5ee878db2b836546566e6198b9a575e3684a5177) for now, and implemented validity state

Thanks!

**Pull request closed without merging**
