### PR TITLE
Don't crash on exceptions in SAX parser

### PR DESCRIPTION
**Pull request by kupietz**
Return false like with the DOM parser

### CODE REVIEW

**Comment by teoric** [comment]
In aaa77c8749b3a629e3313159a23263f6f9f20b4c, I took the opposite path: As the exceptions that come through to this point have nothing to do with parsing (those should be handled by the `ErrorHandler`), it feels cleaner to rethrow them in `validateWithDTDUsingDOM`, too?

**Comment by kupietz** [comment]
> In [aaa77c8](https://github.com/teoric/dtdvalidator/commit/aaa77c8749b3a629e3313159a23263f6f9f20b4c), I took the opposite path: As the exceptions that come through to this point have nothing to do with parsing (those should be handled by the `ErrorHandler`), it feels cleaner to rethrow them in `validateWithDTDUsingDOM`, too?

But then all validation is immediately stopped for all supplied documents when a `SAXParseException`occurs – also with the DOM parser. That's at least not the behaviour we need for DeReKo. Just try validating a document with an unclosed element (and maybe some additional ones). I should have supplied some tests first....

EDIT: Here /tmp/zca15.i5.xml has an unclosed s element:

```
$ time $JAVA_HOME/bin/java -jar target/i5validator-0.1-SNAPSHOT.jar /tmp/zca15.i5.xml  /vol/corpora/DeReKo/current/I5/zca19.i5.xml 
10:03:25.891 [main] INFO  I5Validator - Validating /tmp/zca15.i5.xml using SAX
10:03:25.994 [main] INFO  I5Validator - LOADING ENTITY public: '-//IDS//DTD IDS-I5 1.0//EN' system: 'http://corpora.ids-mannheim.de/I5/DTD/i5.dtd'
10:03:26.054 [main] INFO  I5Validator - LOADING ENTITY public: '-//IDS//ENTITIES Latin 1 Extension for IDS-CES//EN' system: 'http://corpora.ids-mannheim.de/I5/DTD/ids-lat1.ent'
10:03:26.186 [main] ERROR CollectingErrorHandler - /tmp/zca15.i5.xml at 364:139 ERROR The element type "s" must be terminated by the matching end-tag "</s>".
java.lang.RuntimeException: org.xml.sax.SAXParseException; lineNumber: 364; columnNumber: 139; The element type "s" must be terminated by the matching end-tag "</s>".
	at de.mannheim.ids.clarin.xml.I5Validator.validateWithDTDUsingSAX(I5Validator.java:120)
	at de.mannheim.ids.clarin.xml.I5ValidatorRunner.lambda$call$0(I5ValidatorRunner.java:114)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at de.mannheim.ids.clarin.xml.I5ValidatorRunner.call(I5ValidatorRunner.java:68)
	at de.mannheim.ids.clarin.xml.I5ValidatorRunner.call(I5ValidatorRunner.java:24)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at de.mannheim.ids.clarin.xml.I5ValidatorRunner.main(I5ValidatorRunner.java:137)
Caused by: org.xml.sax.SAXParseException; lineNumber: 364; columnNumber: 139; The element type "s" must be terminated by the matching end-tag "</s>".
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at de.mannheim.ids.clarin.xml.I5Validator.validateWithDTDUsingSAX(I5Validator.java:115)
	... 13 more

```

**Comment by teoric** [comment]
OK, my local testing was with too nice files. Please have a look at 1eb1f5718b8e8d12c8b414b0fcebfafe5cbd2b38

This catches the `SAXParseException`s locally and rethrows anything that is not linked to parsing.

**Comment by kupietz** [comment]
> OK, my local testing was with too nice files. Please have a look at [1eb1f57](https://github.com/teoric/dtdvalidator/commit/1eb1f5718b8e8d12c8b414b0fcebfafe5cbd2b38)
> 
> This catches the `SAXParseException`s locally and rethrows anything that is not linked to parsing.

Thanks! That seems to do the job. There shouldn't be any other unforeseen exceptions that should be caught, I guess. Otherwise we'll find out :)

**Pull request closed without merging**
